### PR TITLE
Svg enabled

### PR DESCRIPTION
**Pull request by Pomax**
slowparse - now rolling with SVG power

### CODE REVIEW

**Comment by toolness** [comment]
Other than the test case comments, this looks good!

**Comment by Pomax** [comment]
good points. I'll add some more test cases!

**Comment by Pomax** [comment]
not entirely sure how we want to test mode switching working correctly. put SVG elements outside of an &lt;svg&gt; ancestor and see if it breaks?

**Comment by Pomax** [comment]
one test is to see if

```
<svg>
  <a .../>
</svg>
<a ... >...</a>
```

works or not, since both HTML and SVG have an &lt;a&gt; element

**Pull request merged**
